.TH "src/biblio.h" 3 "Tue May 17 2022" "Fake Mario" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/biblio.h
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <SDL2/SDL\&.h>\fP
.br
\fC#include <SDL2/SDL_image\&.h>\fP
.br
\fC#include <SDL2/SDL_ttf\&.h>\fP
.br
\fC#include <SDL2/SDL_mixer\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBBIBLIO_h\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BIBLIO_h"

.SH "Author"
.PP 
Generated automatically by Doxygen for Fake Mario from the source code\&.
