.TH "donne" 3 "Tue May 17 2022" "Fake Mario" \" -*- nroff -*-
.ad l
.nh
.SH NAME
donne \- class pour stocker les cordonnees des textures de la map  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <map\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
class pour stocker les cordonnees des textures de la map 


.SH "Member Data Documentation"
.PP 
.SS "float donne::x"

.SS "float donne::y"


.SH "Author"
.PP 
Generated automatically by Doxygen for Fake Mario from the source code\&.
