.TH "src/joueur.h" 3 "Tue May 17 2022" "Fake Mario" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/joueur.h
.SH SYNOPSIS
.br
.PP
\fC#include 'biblio\&.h'\fP
.br
\fC#include 'map\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBjoueur\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Fake Mario from the source code\&.
