.TH "src/mafenetre.cpp" 3 "Tue May 17 2022" "Fake Mario" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mafenetre.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'biblio\&.h'\fP
.br
\fC#include 'mafenetre\&.h'\fP
.br
\fC#include 'joueur\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Fake Mario from the source code\&.
