.TH "src/map.cpp" 3 "Tue May 17 2022" "Fake Mario" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/map.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'biblio\&.h'\fP
.br
\fC#include 'map\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "float \fBlev1\fP [3][20]"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "float lev1[3][20]"
\fBInitial value:\fP
.PP
.nf
={
    {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
    {0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0},
    {1,1,1,1,0,1,1,1,0,1,1,1,1,1,0,1,1,1,1,1}
}
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Fake Mario from the source code\&.
