.TH "src/map.h" 3 "Tue May 17 2022" "Fake Mario" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/map.h
.SH SYNOPSIS
.br
.PP
\fC#include 'biblio\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBdonne\fP"
.br
.RI "class pour stocker les cordonnees des textures de la map "
.ti -1c
.RI "class \fBmap\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Fake Mario from the source code\&.
